import { SearchContextProvider } from "./context/search";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SearchContextProvider>
      <html lang="pt">
        <body className={inter.className}>{children}</body>
      </html>
    </SearchContextProvider>
  );
}
